apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secret
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  
  target:
    name: db-creds

  data:
  - secretKey: username                      
    remoteRef:
      key: mysql-cred            
  - secretKey: password                     
    remoteRef:
      key: mysql-cred 
  - secretKey: host                      
    remoteRef:
      key: mysql-cred 
  - secretKey: kenny                      
    remoteRef:
      key: mysql-cred 

