apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secret
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  
  target:
    name: mysql-cred

  data:
  - remoteRef:
      key: mysql-cred
      property: DB_PASSWORD 
    secretKey: DB_PASSWORD
  - remoteRef:
      key: mysql-cred 
      property: DB_HOST 
    secretKey: DB_HOST  
  - remoteRef:
      key: mysql-cred 
      property: DB_DATABASE 
    secretKey: DB_DATABASE 
  - remoteRef:
      key: mysql-cred
      property: DB_USERNAME
    secretKey: DB_USERNAME               
                


